### ISSUE TITLE
Broker does not log nor panic on listener setup errors 

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#1057]
Our connectors do not exit when there’s a problem with them starting and on top of it, on some errors we don’t log what the problem is.

Example problematic config (though others can apply fine):
```
version: 2
services:
  some-connector:
    connector: generic_http
    listenOn: tcp://0.0.0.0:8080
    credentials:
      jwtToken:
        from: literal
        get: some-value
    config:
      headers:
        ClientID: "12345678"
        ClientSecret: "{{ .jwtToken }}"
      forceSSL: true
      match:
        - ^http
```

AC:
- [ ] Add fatal exit on any connector errors
- [ ] Log all startup errors
