### ISSUE TITLE
MSSQL connector fails to connect to an RDS instance via the demo spring app

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#1109]
When pet store is used as the client and secretless is connecting to the xa mssql database (an AWS RDS SQL Server 2017 Express instance), the application fails to interact with the database.

AC:
- [ ] Pet store works over the broker connected to the XA mssql environment

To replicate:
- Create the `secretless.yml` file:
```
version: 2
services:
  mssql:
    connector: mssql
    listenOn: tcp://0.0.0.0:1433
    credentials:
      username: <redacted>
      password: <redacted>
      host: xa-secretless-mssql.<redacted>.us-east-1.rds.amazonaws.com
      port: 1433
```
- Start secretless:
```
$ go run cmd/secretless-broker/main.go -f /path/to/secretless.yml -debug
```
- Check out pet store codebase
- Create a `test.env` file with connection variables:
```
export DB_PLATFORM=mssql
# export DB_URL="sqlserver://xa-secretless-mssql.<redacted>.us-east-1.rds.amazonaws.com;databaseName=SOME_DB_NAME"
export DB_URL=export DB_URL="sqlserver://127.0.0.1;databaseName=SOME_DB_NAME"
export DB_USERNAME="dummy"
export DB_PASSWORD="dummy"
```
- Start pet store:
```
source test.env && mvn package && java -jar ./target/petstore-0.1.0.jar
```

You can then try to add and retrieve the pet:
```
$ curl -s -d '{"name": "test"}' -H "Content-Type: application/json" localhost:8080/pet
$ curl -s -H "Content-Type: application/json" localhost:8080/pets
```

### Expected

No exceptions

### Actual

Exceptions in pet store
