### ISSUE TITLE
MSSQL connector reports "unsupported version" when backend can't be contacted

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#1112]
## Summary

When the broker uses the `mssql` connector and you misconfigure the host/port in `secretless.yml`, connections through the broker will show a misleading error like this:
```
Error: Microsoft ODBC Driver 17 for SQL Server : ODBC Driver 17 for SQL Server does not support connections to SQL Server 2000 or earlier versions.
```

## Steps to Reproduce

- Start `mssql` container:
```
docker run -it -p 2433:1433 -e SA_PASSWORD="yourStrong()Password" -e ACCEPT_EULA=Y mcr.microsoft.com/mssql/server:2017-latest
```
- Create secretless.yml:
```                                                                                                                                                                                                                                               
version: 2
services:
  mssql:
    connector: mssql
    listenOn: tcp://0.0.0.0:3433
    credentials:
      username: sa
      password: yourStrong()Password
      host: 127.0.0.1
      port: 5555
```
- Run secretless with this config
- Connect to the DB with something like this:
```
sqlcmd -S 127.0.0.1,3433 -U dummy -P dummy -d master -Q "select @@version;"
```

## Expected Results
Error that indicates that connection cannot be made

## Actual Results (including error logs, if applicable)
Unsupported driver version error
