### ISSUE TITLE
Secretless configuration files support ssl configuration information

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/secretless-broker#1182]
We are proposing the following supported changes for the secretless yaml, which would allow for ssl configuration within the `config` subsection of a connector in secretless, as its placement in the `credentials` section is unclear.

Example:
```
version: 2

services:
  mssql:
    connector: mssql
    listenOn: 0.0.0.0
    credentials:
      username: foo      
      password: bar
      host: mssql
      port: 0
   config:
      sslmode: require
      sslcert: path/to/cert
 ```
