### ISSUE TITLE
HTTP Generic Connector supports URL parameter injection

### ISSUE THREAD

**Issue by BradleyBoutcher** [cyberark/secretless-broker#1290]
## Is your feature request related to a problem? Please describe.

Certain APIs require the ability to pass authentication data through methods other than `Headers`, which is currently the only supported injection capability of the Generic HTTP connector. To support, more use cases, we would need to allow query params to be passed in by the user's secretless configuration.

## Describe the solution you would like

The Generic HTTP Connector will create an encoded query, attached to the URL passed through Secretless. For example, the user configuration would look like this:
```
services:
  # Injects basic auth credentials and uses http on upstream connection
  basic_auth_http:
    connector: generic_http
    listenOn: tcp://0.0.0.0:8080
    credentials:
      username: someuser
      password: testpassword
      key: somekey
    config:
      credentialPatterns:
        username: '[^:]+'
      headers:
        Authorization: ' Basic {{ printf "%s:%s" .username .password | base64 }}'
      params:
        origin: "foo"
        key: "{{ .key }}"
      authenticateURLsMatching:
        - ^http
```

The keys and values within the `params` section would then be passed into a function for constructing a URL, such as this:
> Note: This example would exist within the `Connect` method of `internal/plugins/http/generic/connector.go`

> Note: `renderedParams` is a placeholder, modeled after `renderedHeaders` in the above file, which uses templating for filling values
```
	// Add configured params to request
	params, err := c.config.renderedParams(credentialsByID)
	if err != nil {
		return fmt.Errorf("failed to render headers: %s", err)
	}
	var query url.Values
	if len(r.URL.RawQuery) > 0 {
		query = r.URL.Query()
	} else {
		query = url.Values{}
	}
	for key, value := range params {
		query.Add(key, value)
	}
	r.URL.RawQuery = query.Encode()
```

So, if the user passed a request such as this through their shell:

```
http_proxy=localhost:9020 curl -X GET "http://httpbin.org/anything" -H "accept: application/json"
```

The final url would look like this, after Secretless does its thing:

```
http://httpbin.org/anything?origin=foo&key=somekey
```

## Additional context

Wikipedia describes the [query string](https://en.wikipedia.org/wiki/Query_string) in more detail.

Postman uses the category `params` for adding or inspecting URL query params, which inspired our naming convention.
