### ISSUE TITLE
PostgreSQL and MySQL connectors support sslmode=verify-full

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#548]
`verify-full` is equivalent to `VERIFY_IDENTITY` as stated in the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode):
> VERIFY_IDENTITY: Like VERIFY_CA, but additionally perform host name identity verification by checking the host name the client uses for connecting to the server against the identity in the certificate that the server sends to the client:

AC:
- [ ] perform host name identity verification by checking the host name the client uses for connecting to the server against the identity in the certificate that the server sends to the client

**Comment by izgeri** [comment]
Note - there was a request to get this fixed in https://github.com/cyberark/secretless-broker/issues/922

**Comment by izgeri** [comment]
Today we briefly looked into what it would take to get this implemented. We noticed the two commented lines:


and wanted to validate whether simply uncommenting them would get this working e2e. It doesn't appear to have worked.

To try to get it working, I cloned the `latest` branch, uncommented these two lines, and ran `./bin/build_darwin`.

I spun up a MySQL instance in a Docker container with:
```
docker run -d -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=myrootpassword -e MYSQL_DATABASE=mydb -e MYSQL_USER=myuser -e MYSQL_PASSWORD=mypassword mysql:5
```
and copied the `ca.pem`, `server-cert.pem`, and `server-key.pem` files from `/var/lib/mysql` into my local dir.

Then I ran `./dist/darwin/amd64/secretless-broker -f secretless.yml` where my secretless config was
```
version: "2"
services:
  test-verify-full:
    protocol: mysql
    listenOn: tcp://localhost:3306
    credentials:
      host: localhost
      port: 3307
      username: myuser
      password: mypassword
      sslmode: verify-full
      sslrootcert:
        from: file
        get: ca.pem
      sslcert:
        from: file
        get: server-cert.pem
      sslkey:
        from: file
        get: server-key.pem
```

I tried to run `mysql -h 127.0.0.1 -P 3306 --ssl-mode=DISABLED`, but I got the error
```
ERROR: 2000 (HY000): tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config
```

Replacing `verify-full` with `verify-ca` got me into the DB.
