### ISSUE TITLE
Secretless has been XAd

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#643]
Key flows:
- [ ] Conjur provider in Kubernetes with PostgreSQL
- [ ] Conjur provider in Kubernetes with MySQL
- [ ] Conjur provider in OpenShift with PostgreSQL
- [ ] Conjur provider in OpenShift with MySQL

**Comment by izgeri** [comment]
All manual tests in the PR template should be run through.

**Comment by jonahx** [comment]
in the course XA, we found in the pg.yml file snippet in the kubernetes tutorial on the live site, the spacing is all borked atm.

**Comment by jonahx** [comment]
## Specific Bugs

- `$remote_appliance_url` is not explained [in this
  section](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-conjur.htm#CreatetheSecretlessBrokerconfiguration)
- Related to above point: Currently port 443 is hardoded, but it's not valid to
  assume the port will always be 443.  Need to update docs so both host and
  port are variables
- Just below that the line 
    ```
    create configmap conjur-ssl-cert --from-file=ssl-certificate="$(cat conjur.pem)"
    ```
  is wrong.  It should be:
    ```
    create configmap conjur-ssl-cert --from-file=ssl-certificate="$(cat conjur.pem)"
    ```
- Port forwaring is not explained anywhere, even though it's required to
  interact with OpenShift. Eg, we had to do:
  ```
  oc port-forward service/conjur-master 8443:443
  ```
- The section [Update Your
  Application](https://docs-staging.secretless.io/Latest/en/Content/Get%20Started/using-conjur.htm#UpdateYourApplication)
  is misleading bc it implies there is some task to do, but in fact it's merely
  explanatory.  We need to be consistent in the doc structure, and make sure
  required steps are clearly delineated from notes and context.

Also, you'll have to issue a new deployment.

- Setting up a host to authenticate via the Kubernetes Authenticator is not
  documented as part of the tutorial.  This includes application of policy. We
  just need to add the policy and explain what it's doing or have a seprate
  tutorial for that.  We had to do:
    ```
    ---
    - !policy
      id: my-service
      body:
      - &variables
        - !variable address
        - !variable username
        - !variable password

      - !group secrets-users

      - !host

      - !grant
        role: !group secrets-users
        member: !host

      - !permit
        resources: *variables
        privileges: [ read, execute ]
        role: !group secrets-users
    ```
- `secretless.yml` is broken...  messed up the configmap.
- "my-service" should be renamed because its a pod, not a k8s service
- "pg.yml" file is borked in k8s tutorial

## General comments

How to get postgres working in OpenShift? This was a rabbit hole. We had to use
a specific image, as well as port-forwarding.

The [Kubernetes
tutorial](https://secretless.io/docs/get_started/kubernetes_tutorial.html) is
k8s specific and assumes minikube. But this wasn't sufficient for OS.  Eg, we
had to use the internal DNS name of the service -- a networking detail we
don't discuss.  For external access, generally port-forwarding is the solution.

Perhaps add a note like: We're going to show you an example that uses
port-forwarding.

**How to login to Openshift**

```
oc login https://openshift-39.itci.conjur.net:8443/ --insecure-skip-tls-verify -u cadmin
```
