### ISSUE TITLE
Configuration parsing in config package handles new config format

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#708]
In this story, the configuration parsing in the config package should be updated to handle the new configuration syntax defined in the [design document](https://github.com/cyberark/secretless-broker/tree/master/design/simpler-configuration.md).

AC:
- [ ] Configuration parser can parse the new syntax, as described above, and map the configuration to the existing configuration objects
- [ ] There are unit tests for the additional code required to parse the new syntax
- [ ] There are more complete unit tests that validate that the configuration parser maintains support for the old syntax
- [ ] The full test suite with no changes to the configuration syntax still passes, indicating that the project still supports the old syntax
- [ ] The data that is parsed from the configuration _may_ contain sensitive data, if it is provided literally. These changes do not expose that sensitive data.
- [ ] The syntax represented in the design document has been faithfully implemented

**Comment by izgeri** [comment]
Why do we have to have all of the http configs in one service def? I feel like we're making this more complicated than it needs to be - couldn't we just have multiple services?

possible http example:

```services:
  - name: conjur_proxy
    protocol: http/conjur
    local_address: /var/docker/conjur-docker.sock # valid file path is socket
    credentials:
      accessToken:
        providerId: name-in-vault
        provider: conjur
      forceSSL:
        providerId: name-in-vault
        provider: conjur
    config:
      requestFilter:
        - pattern: ^http://srdjan.com*
  - name: aws_proxy
    protocol: http/aws
    local_address: /var/docker/aws-docker.sock # valid file path is socket
    credentials:
      accessKeyID:
        providerId: name-in-vault
        provider: conjur
      secretAccessKey:
        providerId: name-in-vault
        provider: conjur
      accessToken:
        providerId: name-in-vault
        provider: conjur
    config:
      requestFilter:
        - pattern: ^http.*```

**Comment by izgeri** [comment]
Also, do we have any more detail about what's going to be actually implemented in this one? I don't think it's written very clearly yet - is this actually updating the config package to take in a secretless config using the new format and parse it appropriately, or is this about something else? Can we add an acceptance criteria to clarify what we expect to be done in this story?

**Comment by sgnn7** [comment]
> Why do we have to have all of the http configs in one service def? I feel like we're making this more complicated than it needs to be - couldn't we just have multiple services?

If you set a proxy env var for your container, you only get one place where all the http data is sent so you need a single endpoint (and thus a single service). We might be supporting a case that's not very common though but that's the reasoning.

**Comment by sgnn7** [comment]
I was reading through k8s/HAProxy/compose configs and I have a slightly different proposal:
```
services:
  aws-client:
    protocol: http/aws
    bind: /var/docker/docker.sock
    credentials:
      aws/accessKeyID:
        providerId: name-in-vault
        provider: conjur
      aws/secretAccessKey:
        providerId: name-in-vault
        provider: conjur
      aws/accessToken:
        providerId: name-in-vault
        provider: conjur
    config:
      pattern: ^http.*

  conjur-client:
    protocol: http/conjur
    bind: 127.0.0.1:8080
    credentials:
      conjur/accessToken:
        providerId: name-in-vault
        provider: conjur
      conjur/forceSSL:
        providerId: name-in-vault
        provider: conjur
    config:
      pattern: ^http://srdjan.com*
```
