### ISSUE TITLE
Secretless rotation XA environment is validated

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#759]
AC:
- [ ] Validate that you can deploy an app with Secretless to the rotation XA environment
- [ ] Set up namespaces for those running perf tests in the rotation XA environment

**Comment by izgeri** [comment]
@ismarc please provide @sgnn7 with the following info (there are definitions in the docs [here](https://docs.secretless.io/Latest/en/Content/Get%20Started/using-dap.htm#RequiredInformation)):

- DB_POLICY_BRANCH (branch with pg address of the form url:port, mysql host/port, user/pass for both)
- DAP_SECRET_LAYER (layer/group with read/execute on secrets)
- DAP_FOLLOWER_NAMESPACE
- DAP_FOLLOWER_URL: https://[service name].[namespace].svc.cluster.local/api
- AUTHENTICATOR_NAME
- DAP_ACCOUNT
- conjur.pem

@sgnn7 I created a new namespace for you `srdjan-secretless-rotation`, but you will still need to:
- load policy to the `conjur/authn-k8s/AUTHENTICATOR_NAME/apps` branch to add your service account host ID to the right layer in policy
  ```yaml
  - !host
    id: srdjan-secretless-rotation/service_account/secretless-rotation
    annotations:
      kubernetes/authentication-container-name: secretless
      openshift: "true"

  # grant membership to the conjur/authn-k8s/AUTHENTICATOR_NAME/apps layer
  - !grant
    role: !layer
    member: !host srdjan-secretless-rotation/service_account/secretless-rotation
  ```
- load policy to `root` to grant your hosts access to the secrets
  ```yaml
  - !grant
    role: !group DAP_SECRET_LAYER
    member: !host conjur/authn-k8s/AUTHENTICATOR_NAME/apps/srdjan-secretless-rotation/service_account/secretless-rotation
  ```
- add a rolebinding to your space so the follower can inject the tokens
  ```yaml
  ---
  kind: RoleBinding
  apiVersion: v1
  metadata:
    name: test-app-conjur-authenticator-role-binding-FOLLOWER_NAMESPACE
    namespace: srdjan-secretless-rotation
  subjects:
    - kind: ServiceAccount
      name: conjur-cluster
      namespace: FOLLOWER_NAMESPACE
  roleRef:
    kind: ClusterRole
    name: conjur-authenticator-FOLLOWER_NAMESPACE
  ```
