### ISSUE TITLE
MySQL handler treats all errors as `malformed packet`

### ISSUE THREAD

**Issue by sgnn7** [cyberark/secretless-broker#766]
## Summary

Regradless of underlying issue, our mysql handler always returns `malformed packet` on all backend problems. This should be a better error, especially for connection problems.

## Steps to Reproduce

_**Note: Since this impacts all errors, there may be simpler ways to do this and even just wrong credentials may likely return this error.**_

- Run and configure an appliance locally
  - `docker run -d --security-opt seccomp:unconfined --name conjur-appliance -p 443:443 -p 5432:5432 -p 1999:1999 conjur-appliance:5.0-stable`
  - `docker exec conjur-appliance evoke configure master -h localhost --master-altnames "127.0.0.1" -p mypassword myorg`
  - Load variables:
```
- !variable
  id: rotation/password

- !variable
  id: rotation/username
```

- Run mysql 5.7
  - `docker run -d -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=myrootpassword -e MYSQL_DATABASE=mydb -e MYSQL_USER=myuser -e MYSQL_PASSWORD=mypassword mysql:5`
- Run Secretless
```
version: 2
services:
  mysql-socket:
    protocol: mysql
    listenOn: unix:///sock/mysql
    credentials:
      username:
        from: conjur
        get: rotation/username
      password:
        from: conjur
        get: rotation/password
      host: 127.0.0.1
      port: 3307
      sslmode: disable
```
- Run juxtaposer:
```
---
driver: mysql-5.7

comparison:
  baselineBackend: mysql_secretless
  recreateConnections: true
  silent: true

formatters:
  stdout:

backends:
  mysql_secretless:
    host: /sock/mysql
```
- Force rotation with this script (requires conjur-api-python binary):
```
#!/bin/bash

PASSWORD="$RANDOM$RANDOM$RANDOM"
PORT=3307

set -x
conjur-py3-cli --insecure -u admin -p mypassword -l https://localhost -a myorg -d variable set rotation/password "$PASSWORD"

mysqlsh --sql \
        --user=root \
        --password=myrootpassword \
        --host=localhost \
        --port=$PORT \
        --ssl-mode=DISABLED \
        -D mydb \
        -e "ALTER USER 'myuser' IDENTIFIED BY '$PASSWORD';"

set +x
echo "OK"
```

## Expected Results

No errors

## Actual Results (including error logs, if applicable)

```
2019/06/24 16:42:30 [494/infinity] mysql_secretless/0                 => Error 2000: Malformed packet
2019/06/24 16:42:30 ERROR sql: Could not execute query!
2019/06/24 16:42:30 ERROR! Query failed!
```

## Additional Information

This can probably be easily replicated with just connecting to mysql with bad credentials as well so that might be easier
