### ISSUE TITLE
htttp/aws service connector always fails to retrieve specified accessKeyId 

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/secretless-broker#816]
## Steps to Reproduce
1. Run Secretless with the follower config below
```
version: 2

services:
  http-aws:
    protocol: http
    listenOn: tcp://0.0.0.0:1234
    credentials:
      accessKeyID: some key id
      secretAccessKey: some key
    config:
      authenticationStrategy: aws
      authenticateURLsMatching:
        - ".*"
```
2. Consume Secretless using the AWS CLI
```
http_proxy=http://localhost:1234 aws sts get-caller-identity --endpoint-url http://sts.amazonaws.com
```

3. See error

## Expected Results

```
{
    "UserId": "some id",
    "Account": "some account",
    "Arn": "arn:aws:iam::somearn"
}
```

## Actual Results (including error logs, if applicable)

The error you get from AWS CLI
```
Unable to parse response (syntax error: line 1, column 0), invalid XML received:
b"AWS connection parameter 'accessKeyId' is not available\n"
```

## Additional Information

Looks like this is due to the secretValue being extracted as `accessKeyID` as opposed to `accessKeyId`, see https://github.com/cyberark/secretless-broker/blob/0589447b88ad37038c2732a3efbf76d5be2196cd/internal/app/secretless/handlers/http/aws.go#L59-L65
