### ISSUE TITLE
Configuration adds support for universal `connector` spec

### ISSUE THREAD

**Issue by izgeri** [cyberark/secretless-broker#826]
The v2 config currently requires that the specific connector protocol that's used is specified in the `protocol` field unless you are using an `http` connector. In that case the `protocol` is specified as `http` and there is a `config.authenticationStrategy` field where the specific protocol implementation is referenced.

```
version: "2"
services:
  aws-proxy:
    protocol: http
    listenOn: tcp://0.0.0.0:8080
    credentials:
      accessKeyId:
        from: env
        get: AWS_ACCESS_KEY_ID
      secretAccessKey:
        from: env
        get: AWS_SECRET_ACCESS_KEY
    config:
      authenticationStrategy: aws
      authenticateURLsMatching:
        - .*
```

This is inconsistent and could be improved. In this effort, we will add support for a new field `connector` that accepts a protocol identifier for _any_ connector type, even a specific instance of an `http` connector. With these changes, the config above would become:

```
version: "2"
services:
  aws-proxy:
    connector: aws
    listenOn: tcp://0.0.0.0:8080
    credentials:
      accessKeyId:
        from: env
        get: AWS_ACCESS_KEY_ID
      secretAccessKey:
        from: env
        get: AWS_SECRET_ACCESS_KEY
    config:
      authenticateURLsMatching:
        - .*
```

AC:
- [x] Config v2 is updated to support specifying `connector` instead of `protocol` or `protocol`/`config.authenticationStrategy`, while maintaining support for the old `protocol` usage
- [x] References to `protocol` and/or `authenticationStrategy` in tests and sample configuration files in the main project repo are updated to use the single `connector` reference instead
- [x] An issue is filed in the docs repo for updating the YAML examples / documentation to use `connector` instead of `protocol` https://github.com/cyberark/secretless-docs/issues/185
