### ISSUE TITLE
A README exists for the generic HTTP connector

### ISSUE THREAD

**Issue by jonahx** [cyberark/secretless-broker#996]
A good place to start would be the notes here:

https://conjurhq.slack.com/archives/CBTETAE20/p1573597938292100

and the sample yaml for recreating the basic auth connector:

```yaml
services:
  http_good_basic_auth:
    connector: generic_http
    listenOn: tcp://0.0.0.0:8080
    credentials:
      username: someuser
      password: testpassword
    config:
      credentialValidation:
        username: [^:]+
      headers:
        Authorization: "Basic {{ Base64(username + ":" + password) }}"
      forceSSL: true
      authenticateURLsMatching:
        - ^http
```

The documentation should include explanations of the connector-specific config fields:
- `credentialValidation`
- `headers` - Specifically, the expected syntax of the curly braces and the functions we provide (currently, just Base64).
- `forceSSL`
